### ISSUE TITLE
TYPO3 12 support

### ISSUE THREAD

**Issue by cheindl** [sitegeist/fluid-styleguide#115]
Dear fluid-styleguide team!

We tried using fluid-styleguide with a new setup TYPO3 12 instance. Unfortunately it is not support yet. Would you be so kind to finish the already started effort (Branch "task/typo312")? Or how could we help to get your a release for TYPO3 12 done?

Kind regards
Christian

**Comment by RostyslavMatviyiv** [comment]
Yeah, support of TYPO3 12 would be just awesome :) And thank you fluid-styleguide team for your efforts! :)

**Comment by ulrichmathes** [comment]
TYPO3 12 support is there
