### ISSUE TITLE
Basic authentication for styleguide

### ISSUE THREAD

**Issue by georgringer** [sitegeist/fluid-styleguide#15]
I would like to see a basic authentication for the styleguide because I would like to deploy that to production but I don't want to have that public available.

I know that I can rename the route but what about some extra safety?

**Comment by s2b** [comment]
In our projects, we use a .htaccess file in combination with environment variables. Thus, this feature won't be part of the styleguide.

**Comment by georgringer** [comment]
maybe you could document that solution?
