### ISSUE TITLE
ZIP-Download

### ISSUE THREAD

**Issue by conpassione** [sitegeist/fluid-styleguide#20]
While trying to download a component (TYPO3 V10/fluid-styleguide 1.4) as zip-file i get the following error:
at Sitegeist\FluidStyleguide\Controller\StyleguideController->downloadComponentZipAction(array('component' => 'Sitegeist\\FluidStyleguide\\DemoComponents\\Molecule\\Teaser'))
in /Users/ba/WebSites/composerdemo/public/typo3conf/ext/fluid_styleguide/Classes/Middleware/StyleguideRouter.php line 137
<img width="1142" alt="grafik" src="https://user-images.githubusercontent.com/15102551/84577333-b4adcc80-adbb-11ea-97c5-cc65edf137f7.png">

**Comment by conpassione** [comment]
To fix change the following lines in File: fluid_styleguide\Classes\Controller\StyleguideController.php 
`145: - public function downloadComponentZipAction(string $component)
         + public function downloadComponentZipAction(array $arguments)`
`151: - $component = $this->sanitizeComponentIdentifier($component);
         + $component = $this->sanitizeComponentIdentifier($arguments['component']);`

**Comment by s2b** [comment]
Thank you for this feedback! I just fixed the bug in master, it will be part of the next release of the extension.
