### ISSUE TITLE
Feature: add support for ext:typo3_encore

### ISSUE THREAD

**Issue by infabo** [sitegeist/fluid-styleguide#37]
Basically for several webpack-features like:

- https://webpack.js.org/guides/code-splitting/
- https://webpack.js.org/guides/caching/
- https://webpack.js.org/guides/development/#using-webpack-dev-server

These webpack features are brought to TYPO3 via [ext:typo3_encore](https://github.com/sabbelasichon/typo3_encore) by providing an integration for [webpack-encore](https://github.com/symfony/webpack-encore).

ext:fluid_styleguide includes JS and CSS assets in plain YAML.

Goal:
Discuss a possible way to use provided APIs by ext:typo3_encore in ext:fluid_styleguide.

**Comment by s2b** [comment]
Yup, totally agree. AssetCollector should also be part of this discussion: https://usetypo3.com/asset-collector.html

**Comment by s2b** [comment]
Fluid Styleguide v1.8.0 introduces a PSR-14 event which can be used to implement this feature. The extension already contains implementations both for Asset Collectors in the TYPO3 Core and EXT:assetcollector, which implements this for TYPO3 v9.

**Comment by infabo** [comment]
Thanks for the PSR-14 events and the reference-implementation for asset collector. I'll have a look and provide a PR to support ext:typo3_encore.

**Comment by infabo** [comment]
Finally I was in need to take a closer look. Unfortunately I did not find a straight forward solution that I could bundle into a PR for ext:fluid_styleguide. Mostly because ext:fluid_styleguide registers its middleware before TSFE-initialization and itself only bootstraps a minimal TSFE instead.

**Comment by georgringer** [comment]
FYI I created a custom extension which combines those 2, if it works I will publish it and add an info here

**Comment by infabo** [comment]
FYI: I created a custom extension too. Not sure if I am allowed to publish.

**Comment by georgringer** [comment]
done. it is published at https://github.com/studiomitte/fluid-styleguide-encore
