### ISSUE TITLE
How to add meta tags to the fluid styleguide

### ISSUE THREAD

**Issue by mbuehrig** [sitegeist/fluid-styleguide#41]
Hi,

How can we add a html meta-tag (e.g. <meta name=“viewport” content=”initial-scale=1, viewport-fit=cover”>) to the fluid styleguide? 

Regards,
Marcel

**Comment by s2b** [comment]
You can either convince me that I should add this to the extension (why do you need it?)...

or you can override the styleguide's templates in your `FluidStyleguide.yaml`:
https://github.com/sitegeist/fluid-styleguide/blob/master/Configuration/Yaml/FluidStyleguide.yaml#L70
