### ISSUE TITLE
Feature: Head scripts / styles in FluidStyleguide.yaml

### ISSUE THREAD

**Issue by katywings** [sitegeist/fluid-styleguide#43]
IS:
Currently you can only add "footer" scripts / styles for components to `Configuration/Yaml/FluidStyleguide.yaml`.

SHOULD:
Ideally it should be possible to add scripts / styles which are rendered in the head of the iframe. Use case: The component accesses some globally defined js variable / library / function - as an example: I wanted to create a little cookie notice component executing the js from https://github.com/AOEpeople/cookie-notice - at the moment I have to use a `window.addEventListener('DOMContentLoaded'...` workaround in the component.

**Comment by s2b** [comment]
Could you check if this works with the associated PR?

**Comment by katywings** [comment]
@s2b Thank you so much for the PR 🤩
