### ISSUE TITLE
TYPO3 10 compatibility

### ISSUE THREAD

**Issue by s2b** [sitegeist/fluid-styleguide#6]
Currently the extension is not compatible with TYPO3 10.x because it relies on the global variable `$GLOBALS['TYPO3_REQUEST']` which was deprecated in with TYPO3 9. This either means a major refactoring because of the chain of dependency injections or another "dirty fix".

I pushed a WIP commit f600161e43ed4e0dcad784a5fa9998edfa98fce7 to branch `typo3-10` which still needs to be tested.

**Comment by georgringer** [comment]
The commit works fine. just one remark: if the site couln't be found (Which is also the case if the site uses https but http is called), then an error will be thrown
```
Return value of Sitegeist\FluidStyleguide\Service\StyleguideConfigurationManager::getCurrentSite() must be an instance of TYPO3\CMS\Core\Site\Entity\Site, instance of TYPO3\CMS\Core\Site\Entity\NullSite returned
```

Proposal is to only allow `TYPO3\CMS\Core\Site\Entity\Site`. especially in 10 a site is always required

**Comment by s2b** [comment]
I think this isn't relevant anymore as this function now returns `SiteInterface`.
