### ISSUE TITLE
Compatibility with fluid_components 3 / TYPO3 11.4

### ISSUE THREAD

**Issue by cheindl** [sitegeist/fluid-styleguide#65]
Hi everybody,

luckily sitegeist/fluid_components is now compatible with TYPO3 11.4; but fluid-styleguide is not yet compatible with fluid_components 3 (or at least composer.json doest not allow it).

Could you please update the fluid_component dependency? IMHO it should be compatible right away.

Kind regards
Christian

**Comment by s2b** [comment]
Unfortunately we need to make some more changes to be compatible again. :( However, we are already working on it, I hope that I can release the new version this week.

**Comment by s2b** [comment]
I just released v2.0.0 of the styleguide, which now supports 10.4 and 11.4 (and requires Fluid Components v3, which has the same requirements).
