### ISSUE TITLE
Possibility to add inlineLanguageLabelFiles

### ISSUE THREAD

**Issue by brosua** [sitegeist/fluid-styleguide#72]
I need a option to add inlineLanguageLabelFiles (like in typoscript) for the styleguide. I´m using the JS object `TYPO3.lang` inside my JS files. If this assets are added to the styleguide, a js error is thrown and the components can´t be used properly.

**Comment by s2b** [comment]
I think the best option is to re-implement the TypoScript functionality in FluidStyleguide.yaml. Let's check if that is possible without too much C&P from core.

**Comment by Atomschinken** [comment]
@brosua Could you please check if #73 solves your issue?

**Comment by brosua** [comment]
Hi, I´m using the styleguide with TYPO3 9.5, so I can´t test this. I implemented the same and found one thing:

- Function `getLabelsFromLocalizationFile ` I needed following line `$language = $GLOBALS['LANG']->lang ?? 'default';`. Maybe this is an issue with TYPO3 9.5

Apart from that, everything works. 
I think it would be better to add the inlineLanguageFiles not inside the IFrame Layout. Instead you can add it to the Styleguide Layout.

**Comment by Atomschinken** [comment]
Hi @brosua,
thank you for testing.
Where did you add this line `$language = $GLOBALS['LANG']->lang ?? 'default';` ?
In the function `getLabelsFromLocalizationFile` it should already be there 🤔  

> I think it would be better to add the inlineLanguageFiles not inside the IFrame Layout. Instead you can add it to the Styleguide Layout.

Wouldn't this mean that you need to use `parent.` in your component as they are loaded in iframes?

**Comment by brosua** [comment]
Hi @Atomschinken ,
yes, you added a similiar line, but without `->lang` `($GLOBALS['LANG'] ?? 'default')` :) maybe, this is a difference between  version 9 and 11

Second question: Yes, you´re right. Your implementation is fine.

**Comment by Atomschinken** [comment]
This feature won't be part of the styleguide in the near future. So i'm closing this issue for now.
