### ISSUE TITLE
Make "content" and "class" editable 

### ISSUE THREAD

**Issue by sascha-egerer** [sitegeist/fluid-styleguide#92]
Do don't understand why `class` and `content` are not editible in the "edit mode". https://github.com/sitegeist/fluid-styleguide/blob/c16540a328811a5ac7f573d5c2fab515f5da76cb/Resources/Private/Components/Molecule/EditFixtures/EditFixtures.html#L11

What is the reason to exclude these properties from the edit view?

**Comment by s2b** [comment]
Good question. 🙂 I can't think of a good reason other than that it might be confusing if the component doesn't use those variables.

If you like these values to be editable, you can create a pull request. The editor could also be improved in other ways, for example it could be possible to edit certain data structures like Typolink or DateTime.

**Comment by sascha-egerer** [comment]
Ok, so in the first step i would just allow them to be editable. You're right that it may be confusing if they are not used but i don't think there is a way to figure out if it is used.

**Comment by sascha-egerer** [comment]
I think we could also an option to a component to disable one of these 2 variables in edit mode if required.
