### ISSUE TITLE
Wrong public url for assets when using typo3/cms-composer-installers

### ISSUE THREAD

**Issue by Tim-Obert** [sitegeist/fluid-styleguide#99]
If using typo3/cms-composer-installers the assets urls are resulting in an 404.
The generated path is e. g.: 
`sitegeist/fluid-styleguide/Resources/Public/Css/Styleguide.min.css?1669727665`

With cms-composer -installers the extensions are in vendor and with that not publicly accessable. The right path would be: 
`/_assets/0f8f28c7d297f47d804fd32b8d6d5018/Css/Styleguide.min.css`

If `PathUtility::getAbsoluteWebPath($path, false)` would be used instead of `PathUtility::stripPathSitePrefix(GeneralUtility::getFileAbsFileName($path))` the right public path would be generated.

**Comment by s2b** [comment]
Thank your for the contribution!
